services:
  - name: google
    url: https://google.com
    interval: 5

  - name: github
    url: http://github.com
    interval: 10

  - name: githubb
    url: http://githubb.com
    interval: 5

telegram:
  botToken: "8745721723:AAEaqPczKkkyroML5xS6Y2mK8yF64grIobA"
  chatID: "1804094825"
  failureThreshold: 3
